#Pull request check
name: Pull Request Checks

on:
  pull_request:
    branches:
      - main

jobs:
  scan:
    name: Static Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install bandit safety detect-secrets

      - name: Run SAST with Bandit
        run: bandit -r .

      - name: Detect secrets
        run: detect-secrets scan
        
      - name: Check for vulnerabilities in dependencies
        run: |
          pip install safety
          safety check --full-report